config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :views
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'games#index'
  
  resources :games do
    resources :score_cards
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :score_cards

  def open_for_score_submissions
    if self.number_of_players > self.score_cards.count
      true
    else
      false
    end
  end
end

app/models/score_card.rb
class ScoreCard < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :wonder, presence: true

  enum wonder: { 'Abu Simbel (A)': 0, 'Abu Simbel (B)': 1,
                'Babylon (A)': 2, 'Babylon (B)': 3,
                'Great Wall (A)': 4, 'Great Wall (B)': 5}

  def culture_score
    self.blue_points
  end

  def commerce_score
    self.yellow_points
  end

  def cities_score
    self.black_points
  end

  def guild_score
    self.purple_points
  end

  def leader_score
    self.leader_points
  end

  def fleet_score
    self.fleet_points
  end

  def wonder_score
    self.wonder_points
  end

  def coin_score
    (self.coin_total / 3).floor - self.debt_total
  end

  def military_score
    self.plus_one_victory_tokens +
    (self.plus_three_victory_tokens * 3) +
    (self.plus_five_victory_tokens * 5) +
    self.plus_seven_victory_tokens -
    self.minus_one_defeat_tokens -
    (self.minus_two_defeat_tokens * 2) -
    (self.minus_three_defeat_tokens * 3)
  end

  def babel_score
    self.great_project_token_points -
    self.great_project_penalty_points +
    case self.babel_tiles_played
    when 0
      0
    when 1
      2
    when 2
      5
    when 3
      10
    end
  end

  def  science_score
    cogs = self.cog_science_symbols
    tablets = self.tablet_science_symbols
    compasses = self.compass_science_symbols
    wildcards = self.wildcard_science_symbols

    case wildcards
    when 0
      count_science_points([cogs, tablets, compasses])

    when 1
      opt1 = [cogs + 1, tablets, compasses]
      opt2 = [cogs, tablets + 1, compasses]
      opt3 = [cogs, tablets, compasses + 1]
      options = [
        count_science_points(opt1),
        count_science_points(opt2), 
        count_science_points(opt3)
      ]
      options.max

    when 2
      opt1 = [cogs + 2, tablets, compasses]
      opt2 = [cogs, tablets + 2, compasses]
      opt3 = [cogs, tablets, compasses + 2]
      opt4 = [cogs + 1, tablets + 1, compasses]
      opt5 = [cogs + 1, tablets, compasses + 1]
      opt6 = [cogs, tablets + 1, compasses + 1]
      options = [
        count_science_points(opt1),
        count_science_points(opt2),
        count_science_points(opt3),
        count_science_points(opt4),
        count_science_points(opt5),
        count_science_points(opt6)
      ]
      options.max

    when 3
      opt1 = [cogs + 3, tablets, compasses]
      opt2 = [cogs, tablets + 3, compasses]
      opt3 = [cogs, tablets, compasses + 3]
      opt4 = [cogs + 2, tablets + 1, compasses]
      opt5 = [cogs + 2, tablets, compasses + 1]
      opt6 = [cogs + 1, tablets + 2, compasses]
      opt7 = [cogs, tablets + 2, compasses + 1]
      opt8 = [cogs + 1, tablets, compasses + 2]
      opt9 = [cogs, tablets + 1, compasses + 2]
      opt10 = [cogs + 1, tablets + 1, compasses + 1]
      options = [
        count_science_points(opt1),
        count_science_points(opt2),
        count_science_points(opt3),
        count_science_points(opt4),
        count_science_points(opt5),
        count_science_points(opt6),
        count_science_points(opt7),
        count_science_points(opt8),
        count_science_points(opt9),
        count_science_points(opt10)
      ]
      options.max
    end #end case wildcards
  end

  def count_science_points array
    fail "Array must have 3 integer values" unless array.count == 3

    array[0]**2 +
    array[1]**2 +
    array[2]**2 +
    if array[0] > 0 && array[1] > 0 && array[2] > 0
      array.min * 7
    else
      0
    end
  end

  def calculate_score
    self.culture_score +
    self.commerce_score + 
    self.cities_score +
    self.guild_score + 
    self.leader_score +
    self.fleet_score +
    self.wonder_score +
    self.coin_score +
    self.military_score +
    self.babel_score + 
    self.science_score
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games
  has_many :score_cards
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = current_user.games.create(game_params)

    if @game.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  
  def game_params
    params.require(:game).permit(:number_of_players,
      :leaders_expansion,
      :cities_expansion,
      :armada_expansion,
      :great_projects_expansion,
      :babel_expansion
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/score_cards_controller.rb
class ScoreCardsController < ApplicationController
  before_action :authenticate_user!

  def new
    @score_card = ScoreCard.new
    @game = Game.find(params[:game_id])
  end

  def create
    @game = Game.find(params[:game_id])
    new_score_card = @game.score_cards.create(score_card_params.merge(user: current_user))
    if new_score_card.valid?
      new_score_card.update_attribute(:total_score, new_score_card.calculate_score)
      redirect_to game_path(@game)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  def score_card_params
    params.require(:score_card).permit(
      :wonder,
      :plus_one_victory_tokens,
      :plus_three_victory_tokens,
      :plus_five_victory_tokens,
      :plus_seven_victory_tokens,
      :minus_one_defeat_tokens,
      :minus_two_defeat_tokens,
      :minus_three_defeat_tokens,
      :coin_total,
      :debt_total,
      :wonder_points,
      :blue_points,
      :yellow_points,
      :black_points,
      :purple_points,
      :tablet_science_symbols,
      :cog_science_symbols,
      :compass_science_symbols,
      :wildcard_science_symbols,
      :leader_points,
      :fleet_points,
      :great_project_token_points,
      :great_project_penalty_points,
      :babel_tiles_played,
      :total_score
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/score_cards_helper.rb
module ScoreCardsHelper
end

app/views/games/index.html.erb
<h1>7 Wonders: Game Tracker</h1>

<div class="button-stack">
  <%= link_to new_game_path do %>
    <button>Create New Game</button>
  <% end %>
</div>

<div>
  <% @games.order(created_at: :desc).each do |game| %>
    <%= link_to game_path(game) do %>
      <div class="game-box">
        <span class="game-date">
          #<%= game.id %> - <%= game.created_at.strftime('%D') %>
        </span>
        <br/>
        <p>Players: <%= game.number_of_players %></p>
        <span>Expansions: </span>
        <ul>
          <% if game.leaders_expansion %>
            <li>Leaders</li>
          <% end %>
          <% if game.cities_expansion %>
            <li>Cities</li>
          <% end %>
          <% if game.armada_expansion %>
            <li>Armada</li>
          <% end %>
          <% if game.great_projects_expansion %>
            <li>Great Projects</li>
          <% end %>
          <% if game.babel_expansion %>
            <li>Tower of Babel</li>
          <% end %>
        </ul>
      </div>
    <% end %> <%# end link_to game_path(game) do %>
  <% end %> <%# end @games.each do %>
</div>

app/views/games/new.html.erb
 <div class="game-form-box"> 
  <h1>Create a New Game</h1>

  <%= simple_form_for @game do |f| %>
    <%= f.input :number_of_players, required: true, default: 2 %>
    <%= f.input :leaders_expansion, as: :boolean %>
    <%= f.input :cities_expansion, as: :boolean %>
    <%= f.input :armada_expansion, as: :boolean %>
    <%= f.input :great_projects_expansion, as: :boolean %>
    <%= f.input :babel_expansion, as: :boolean %>
    <br/>
    <%= f.button :submit %>
    <%= link_to games_path do %>
      <button>Cancel</button>
    <% end %>
  <% end %>
</div>

app/views/games/show.html.erb
<h1><%= link_to '◀︎', games_path, class: "decorated-link" %> Game #<%= @game.id %></h1>
<div class="game-box">
  <span class="game-date"><%= @game.created_at.strftime('%D') %></span>
  <br/>
  <p>Players: <%= @game.number_of_players %></p>
  <span>Expansions:</span>
  <ul>
    <% if @game.leaders_expansion %>
      <li>Leaders</li>
    <% end %>
    <% if @game.cities_expansion %>
      <li>Cities</li>
    <% end %>
    <% if @game.armada_expansion %>
      <li>Armada</li>
    <% end %>
    <% if @game.great_projects_expansion %>
      <li>Great Projects</li>
    <% end %>
    <% if @game.babel_expansion %>
      <li>Tower of Babel</li>
    <% end %>
  </ul>
</div>
<br/>
<% if @game.open_for_score_submissions %>
  <div class="button-stack">
    <%= link_to new_game_score_card_path(@game) do %>
      <button>Submit Score</button>
    <% end %>
  </div>
<% end %>
<br/>
<% if @game.score_cards.any? %>
  <h3>Scores</h3>
  <% @game.score_cards.order(total_score: :desc, coin_total: :desc).each do |sc| %>
    <div class="score-card-box">
      <span><%= sc.user.email %></span>
      <br/>
      <span><%= sc.wonder %></span>
      <br/>
      <span>Score: <%= sc.total_score %> - <%=sc.coin_total %>g</span>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    
    <div class="main">
      <%= yield %>
    </div>

    <footer>
      <div class="footer-div">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <button>Logout</button>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <button>Log In</button>
          <% end %>
        <% end %>
      </div>
    </footer>
  </body>
</html>

app/views/pages/index.html.erb
<div class="content">
  <h1 class="non-black">Hello, World!</h1>
</div>

app/views/score_cards/new.html.erb
<div class="score-card-form-box"> 
  <h1>Total Your Points</h1>
  <h4>Player: <%= current_user.email %></h4>
  <br/>
  <%= simple_form_for @score_card, url: game_score_cards_path(@game) do |f| %>
    <%= f.input :wonder, collection: ScoreCard.wonders.keys %>
    <%= f.input :plus_one_victory_tokens %>
    <%= f.input :plus_three_victory_tokens %>
    <%= f.input :plus_five_victory_tokens %>
    <% if @game.armada_expansion %>
      <%= f.input :plus_seven_victory_tokens %>
    <% end %>
    <%= f.input :minus_one_defeat_tokens %>
    <% if @game.armada_expansion %>
      <%= f.input :minus_two_defeat_tokens %>
      <%= f.input :minus_three_defeat_tokens %>
    <% end %>
    <%= f.input :coin_total %>
    <% if @game.cities_expansion || @game.armada_expansion %>
      <%= f.input :debt_total %>
    <% end %>
    <%= f.input :wonder_points %>
    <%= f.input :blue_points %>
    <%= f.input :yellow_points %>
    <% if @game.cities_expansion %>
      <%= f.input :black_points %>
    <% end %>
    <%= f.input :purple_points %>
    <%= f.input :tablet_science_symbols %>
    <%= f.input :cog_science_symbols %>
    <%= f.input :compass_science_symbols %>
    <%= f.input :wildcard_science_symbols %>
    <% if @game.leaders_expansion %>
      <%= f.input :leader_points %>
    <% end %>
    <% if @game.armada_expansion %>
      <%= f.input :fleet_points %>
    <% end %>
    <% if @game.great_projects_expansion %>
      <%= f.input :great_project_token_points %>
      <%= f.input :great_project_penalty_points %>
    <% end %>
    <% if @game.babel_expansion %>
      <%= f.input :babel_tiles_played %>
    <% end %>
    <br/>
    <%= f.submit 'Submit Your Score'%>
    <%= link_to game_path(@game) do %>
      <button>Cancel</button>
    <% end %>
  <% end %>
</div>